### ISSUE TITLE
Code: Add default mirror to install call

### ISSUE THREAD

**Issue by llnelson** [nationalparkservice/DRR_Template#11]
This helps since folks don't have consistent R configurations. See [DRR_Template.Rmd](https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/DRR_Template.Rmd) for a location where this should be used.

`if (length(pkgList[!inst]) > 0) {
  install.packages(pkgList[!inst], dep = TRUE, quiet = TRUE,
                   repos = "https://cloud.r-project.org")
}`

**Comment by RobLBaker** [comment]
Thanks! Done!
